server.ip = "0.0.0.0"
server.port = 4567
server.systemTrayEnabled = false
server.initialOpenInBrowserEnabled = false
server.extensionRepos = [
    "https://raw.githubusercontent.com/keiyoushi/extensions/repo/index.min.json"
]

